name: self_hosted_runner

on: push

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: NPM setup
        run: npm install

      - name: Check NPM
        run: npm run check

      - name: Test NPM
        run: npm test

      - name: Save Test Result
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: reports/junit.xml

  deploy:
    runs-on: self-hosted
    needs: test

    steps:
      - name: Download Test Result
        uses: actions/download-artifact@v4
      
      - name: Display Test Result
        run: cat test-result/junit.xml